config/routes.rb
Project::Application.routes.draw do

  get "checkout/index"

  get "checkout/calculate"

  root :to => "Application#index", :via => :get

  get "comic_orders/index"

  get "comic_orders/new"

  get "orders/index"

  get "orders/new"

  get "comics/index"

  get "comics/new"

  match "comics/:id" => "comics#show", :as => "comic_page", :via => :get
  match "comics/search/:publisher" => "comics#search_publisher", :as => "search_publisher_page", :via => :get
  match "comics/search/:price" => "comics#search_price", :as => "search_price_page", :via => :get 
  match "comics/search" => "Application#search", :as => "search_comics", :via => :post

  match "cart" => "Application#cart", :via => :get
  match "cart/add" => "comics#add", :as => "add_item"
  match "cart/remove" => "comics#remove", :as => "remove_item"
  match "cart/checkout" => "checkout#index"
  match "cart/checkout/total" => "checkout#calculate", :via => :post

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/comic.rb
class Comic < ActiveRecord::Base
  attr_accessible :description, :name, :price, :publisher, :stock_quantity, :url

  validates :description, :name, :price, :publisher, :stock_quantity, presence: true
  validates :price, :stock_quantity, numericality: true

  has_many :comic_orders
end

app/models/comic_order.rb
class ComicOrder < ActiveRecord::Base
  attr_accessible :comic_id, :order_id, :price, :quantity

  validates :price, :quantity, numericality: true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :address, :city, :country, :first_name, :id, :last_name, :postal_code, :province_id

  validates :address, :city, :country, :first_name, :last_name, presence: true

  belongs_to :province 
  has_many :orders

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :customer_id, :gst_rate, :hst_rate, :id, :pst_rate, :status

  belongs_to :customer
  has_many :comic_orders
end

app/models/province.rb
class Province < ActiveRecord::Base
  attr_accessible :gst, :hst, :name, :pst

  validates :name, presence: true
  validates :gst, :hst, :pst, numericality: true

  has_many :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def index
  	if session[:total].nil?
  		session[:total] = 0
  	end
  	if session[:cart].nil?
  		session[:cart] = []
  	end

  	@comics = Comic.order("name")
  end

  def search
  	@comics = Comic.where("name LIKE '%#{params[:keywords]}%' OR publisher LIKE '%#{params[:keywords]}%'")
  end

  def cart
  	@comics = session[:cart]
  end
  
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def index
  	@total = session[:total]
  	@items = session[:cart]
  	@customer = Customer.new
  	@provinces = Province.all
  end

  def calculate
  	#@id = params[:province_id]
  	tax = 0.1
  	@total = session[:total]
  	@items = session[:cart]
  	@taxes = @total * tax
  end
end

app/controllers/comic_orders_controller.rb
class ComicOrdersController < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  helper_method :add
  def index
  end

  def new
  end

  def show
  	@comic = Comic.find(params[:id])
  end

  def search_publisher
  	pub = params[:publisher].slice(0,1).capitalize + params[:publisher].slice(1..-1)
  	@comics = Comic.where(:publisher => pub)
  end

  def search_price
    if params[:price] = "less than 10" then
      search_string = "price < 10"
    end
    @comics = Comic.where(search_string)
  end

  def add
    comic = Comic.find(params[:comic])
    session[:total] += comic.price
    session[:cart] << comic
    redirect_to "/cart"
  end

  def remove
    comic = Comic.find(params[:comic])

    session[:cart].delete_if {|x| x.id == comic.id}
    session[:total] -= comic.price 
    redirect_to "/cart"
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
  	@customers = Customer.all
  end
  
  def new
    @customer = Customer.new
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/comic_orders_helper.rb
module ComicOrdersHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/application/_banner.html.erb
<div id="banner">
	<%= image_tag("banner.jpg") %>
	<%= link_to "/cart", :class => "cart" do %>
		<section id="cart">
			<b>Cart</b><br/>
			<b>Total: </b><%= number_to_currency(session[:total]) %><br/>
			<b>Items: </b><%= session[:cart].count %>
		</section>
	<% end %>
</div>

app/views/application/_footer.html.erb
<div id="footer">
	<p>Made by Preston Sutherland</p>
</div>

app/views/application/_menu.html.erb
<div id="menu">
	
	
	<ul>
		<li class="list_header">Publisher</li>
		<li><%= link_to "Marvel", search_publisher_page_path(:publisher => "Marvel") %></li>
		<li><%= link_to "DC Comics", search_publisher_page_path(:publisher => "DC Comics") %></li>
		<li class="list_header">Price</li>
		<li><%= link_to "Less than $10", search_price_page_path(:price => "less than 10") %></li>
		<li>Between $10 - $20</li>
		<li>Greater than $20</li>
	</ul>

</div>

app/views/application/_navlist.html.erb
<div id="nav">
	<ul id="navlist">
		<li><%= link_to "Home", root_url %></li>
		<li><%= link_to "About", "./" %></li>
		<li><%= link_to "Contact", "./" %></li>
	</ul>

	<%= form_tag search_comics_path, :class => "search" do %>
		<%= text_field_tag :keywords %>
		<%= submit_tag "Search" %>
	<% end %>

</div>

app/views/application/cart.html.erb
<div id="container">
	
	<%= render "banner" %>
	<%= render "navlist" %>

	<div id="content">		
		<%= render "menu" %>

		<div id="info">
			<p>Number of Items: <%= session[:cart].count %></p>
			<p>Cart Total: <%= number_to_currency(session[:total]) %></p>
			<% @comics.each do |comic| %>
				<%= render :partial => "comics/cartcomic", :object => comic, :as => "comic" %>
			<% end %> 

			<% if session[:cart].count == 0 then %>
				<p>You have no items in your cart</p>
			<% else %>
				<%= link_to "Checkout", "/cart/checkout" %>
			<% end %>
		</div>

	</div>

	<%= render "footer" %>

</div>

app/views/application/index.html.erb
<div id="container">
	
	<%= render "banner" %>
	<%= render "navlist" %>

	<div id="content">		
		<%= render "menu" %>

		<div id="info">
			<% @comics.each do |comic| %>
				<%= render comic %>
			<% end %> 
		</div>

	</div>

	<%= render "footer" %>

</div>

app/views/application/search.html.erb
<div id="container">
	
	<%= render "banner" %>
	<%= render "navlist" %>

	<div id="content">		
		<%= render "menu" %>

		<div id="info">
			<% @comics.each do |comic| %>
				<%= render comic %>
			<% end %> 
		</div>

	</div>

	<%= render "footer" %>

</div>

app/views/checkout/_info.html.erb
<%= form_tag("/cart/checkout/total") do %>
 
  <div class="field">
    <%= label_tag(:first_name, "First Name: ") %>
    <%= text_field_tag :first_name %>
  </div>
  <div class="field">
    <%= label_tag(:last_name, "Last Name: ") %>
    <%= text_field_tag :last_name %>
  </div>
  <div class="field">
    <%= label_tag(:address, "Address: ") %>
    <%= text_field_tag :address %>
  </div>
  <div class="field">
    <%= label_tag(:city, "City: ") %>
    <%= text_field_tag :city %>
  </div>
  <div class="field">
    <%= label_tag(:postal_code, "Postal Code: ") %>
    <%= text_field_tag :postal_code %>
  </div>
  <div class="field">
    <%= label_tag(:province_id, "Province: ") %>
    <%= collection_select(@customer, :province_id, @provinces, :id, :name, :selected => :province_id) %>
  </div>
  <div class="field">
    <%= submit_tag "Proceed with Checkout" %>
  </div>
<% end %>

app/views/checkout/calculate.html.erb
<div id="container">
	
	<%= render "banner" %>
	<%= render "navlist" %>

	<div id="content">		
		<%= render "menu" %>

		<div id="info">
			
			<h3>Checkout</h3>

			<p><b>Subotal: </b><%= number_to_currency(@total) %></p>
			<p><b>Taxes: </b><%= number_to_currency(@taxes) %></p>
			<p><b>Total: </b><%= number_to_currency(@taxes + @total) %></p>

		</div>

	</div>

	<%= render "footer" %>

</div>

app/views/checkout/index.html.erb
<div id="container">
	
	<%= render "banner" %>
	<%= render "navlist" %>

	<div id="content">		
		<%= render "menu" %>

		<div id="info">
			
			<h3>Checkout</h3>

			<%= render "info" %>

			<p><b>Checkout Total: </b><%= number_to_currency(@total) %></p>

		</div>

	</div>

	<%= render "footer" %>

</div>

app/views/comic_orders/index.html.erb
<h1>ComicOrders#index</h1>
<p>Find me in app/views/comic_orders/index.html.erb</p>

app/views/comic_orders/new.html.erb
<h1>ComicOrders#new</h1>
<p>Find me in app/views/comic_orders/new.html.erb</p>

app/views/comics/_cartcomic.html.erb
<div class="cartcomic">
	<%= image_tag(comic.url) %>
	<h4><%= link_to comic.name, comic_page_path(comic) %></h4>
	<span class="price"><b>Publisher: </b><%= comic.publisher %></span>
	<span class="price"><b>Price: </b><%= comic.price %></span>

	<p><%= link_to "Remove from cart", remove_item_path(:comic => comic.id) %></p>
</div>

app/views/comics/_comic.html.erb
<%= link_to comic_page_path(comic) do %>
<div class="comic">
	<%= image_tag(comic.url) %>
	<h4><%=  comic.name %></h4>
	<span class="price"><b>Publisher: </b><%= comic.publisher %></span>
	<span class="price"><b>Price: </b><%= comic.price %></span>
</div>
<% end %>

app/views/comics/index.html.erb
<h1>Comics#index</h1>
<p>Find me in app/views/comics/index.html.erb</p>

app/views/comics/new.html.erb
<h1>Comics#new</h1>
<p>Find me in app/views/comics/new.html.erb</p>

app/views/comics/search_price.html.erb
<div id="container">
	
	<%= render "banner" %>
	<%= render "navlist" %>

	<div id="content">		
		<%= render "menu" %>

		<div id="info">
			<% @comics.each do |comic| %>
				<%= render comic %>
			<% end %> 
		</div>

	</div>

	<%= render "footer" %>

</div>

app/views/comics/search_publisher.html.erb
<div id="container">
	
	<%= render "banner" %>
	<%= render "navlist" %>

	<div id="content">		
		<%= render "menu" %>

		<div id="info">
			<% @comics.each do |comic| %>
				<%= render comic %>
			<% end %> 
		</div>

	</div>

	<%= render "footer" %>

</div>

app/views/comics/show.html.erb
<div id="container">
	
	<%= render "banner" %>
	<%= render "navlist" %>

	<div id="content">		
		<%= render "menu" %>

		<div id="info">

			<h1><%= @comic.name %></h1>
			<%= image_tag(@comic.url, :class => "show_image") %>
			<p><b>Description:</b><%= @comic.description %></p>
			<p><b>Price:</b><%= @comic.price %></p>
			<p><b>Stock Quantity:</b><%= @comic.stock_quantity %></p>
			<%= link_to "Add to cart", add_item_path(:comic => @comic.id) %>			
			
		</div>

	</div>

	<%= render "footer" %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>